export const projects = [
  {
    year: '2019',
    name: 'SMART SMK',
    tools: ['Laravel', 'Bootstrap', 'jQuery'],
    link: '',
  },
  {
    year: '2019',
    name: 'SMKN 13 BANDUNG Library Guestbook',
    tools: ['HTML', 'PHP', 'Bootstrap', 'jQuery'],
    link: '',
  },
  {
    year: '2019',
    name: 'SMKN 13 BANDUNG School Cooperatives Store Cashier',
    tools: ['HTML', 'PHP', 'Bootstrap', 'jQuery'],
    link: '',
  },
  {
    year: '2019',
    name: 'PRiADI CRM',
    tools: ['Codeigniter', 'Bootstrap', 'jQuery'],
    link: '',
  },
  {
    year: '2020',
    name: 'PRiADI.id',
    tools: ['Codeigniter', 'Bootstrap', 'jQuery'],
    link: 'https://priadi.id',
  },
  {
    year: '2020',
    name: 'PRiADI CBT',
    tools: ['Codeigniter', 'Bootstrap', 'jQuery'],
    link: 'http://test.priadi.id',
  },
  {
    year: '2021',
    name: 'SID-DK-Haji',
    tools: ['Android Studio', 'Retrofit', 'Java'],
    link: '',
  },
  {
    year: '2021',
    name: 'PRiADI Corporate Dashboard',
    tools: ['Codeigniter', 'Bootstrap', 'jQuery'],
    link: '',
  },
  {
    year: '2022',
    name: 'PRiADI Test Desktop',
    tools: ['JavaFX'],
    link: '',
  },
  {
    year: '2022',
    name: 'PRiADI Appointment Maker',
    tools: ['Codeigniter', 'jQuery'],
    link: '',
  },
  {
    year: '2022',
    name: 'PRiADI Recruitment Dashboard',
    tools: ['Codeigniter', 'Bootstrap', 'jQuery'],
    link: '',
  },
  {
    year: '2022',
    name: 'PRiADI Customer Service',
    tools: ['Flutter', 'Retrofit', 'Django'],
    link: '',
  },
  {
    year: '2022',
    name: 'PRiADI Finger Test',
    tools: ['Vue.js', 'Bootstrap', 'Django', 'OpenCV'],
    link: 'https://apps.priadi.id',
  },
  {
    year: '2023',
    name: 'PRiADI Finger Test Mobile',
    tools: ['Flutter', 'OpenCV', 'Django'],
    link: '',
  },
  {
    year: '2023',
    name: 'Nekochigura (Static)',
    tools: ['HTML & CSS', 'Bootstrap'],
    link: 'https://pratamafikri.github.io/nekochigura',
  },
  {
    year: '2023',
    name: 'Portfolio v.1',
    tools: ['React', 'Tailwind CSS'],
    link: 'https://fukurou-shi.vercel.app',
  },
  {
    year: '2023',
    name: 'PRiADI HRIS',
    tools: ['Codeigniter', 'Bootstrap'],
    link: '',
  },
  {
    year: '2023',
    name: 'Kanbanwa (Trello Clone)',
    tools: ['Flutter', 'Firebase'],
    link: 'https://github.com/denasusan/todo_app',
  },
  {
    year: '2024',
    name: 'Portfolio v.2',
    tools: ['Next.js', 'Typescript', 'Tailwind CSS'],
    link: 'https://fikri-mf.vercel.app',
  },
  {
    year: '2024',
    name: 'Fukurou Space',
    tools: ['Next.js', 'Typescript', 'Tailwind CSS'],
    link: 'https://fukurou-space.vercel.app',
  },
]
